#define KLS_KLU_INT_VARIANT 1
#define KLS_KLU_KERNEL_CHUNKS_FREE KLS_KLU32_KERNEL_CHUNKS_FREE
#define KLS_KLU_KERNEL_FINISH KLS_KLU32_KERNEL_FINISH
#define KLS_KLU_KERNEL_INIT KLS_KLU32_KERNEL_INIT
#define KLS_KLU_KERNEL_LEVELS KLS_KLU32_KERNEL_LEVELS
#define KLS_KLU_KERNEL_PIPE KLS_KLU32_KERNEL_PIPE
#define KLS_KLU_KERNEL_ROW KLS_KLU32_KERNEL_ROW
#define KLS_KLU_KERNEL_STEP KLS_KLU32_KERNEL_STEP
#define KLS_SN_PANEL_FACTOR KLS32_SN_PANEL_FACTOR
#define kls_klu_dense_tail kls32_klu_dense_tail
#define kls_klu_pipe_det kls32_klu_pipe_det
#define kls_klu_pipe_nopanels kls32_klu_pipe_nopanels
#define kls_klu_pipe_threads kls32_klu_pipe_threads
#define kls_pipe_finish_threads kls32_pipe_finish_threads
#include "../third_party/suitesparse/KLU/Source/trilinos_klu_l_kernel.c"
